export const MOCK_USAGE_SUMMARY = {
  bandwidth: {
    id: 'bandwidth',
    title: 'Bandwidth',
    used: 42.5,
    limit: 100,
    unit: 'GB',
    percent: 42.5,
    remaining: 57.5,
    trend: '+12.4%',
    isUp: true,
    color: 'indigo',
  },
  storage: {
    id: 'storage',
    title: 'Storage',
    used: 12.8,
    limit: 50,
    unit: 'GB',
    percent: 25.6,
    remaining: 37.2,
    trend: '+4.1%',
    isUp: true,
    color: 'purple',
  },
  build_minutes: {
    id: 'build_minutes',
    title: 'Build Minutes',
    used: 320,
    limit: 1000,
    unit: 'mins',
    percent: 32.0,
    remaining: 680,
    trend: '-8.5%',
    isUp: false,
    color: 'amber',
  },
  function_executions: {
    id: 'function_executions',
    title: 'Function Executions',
    used: 450,
    limit: 1000,
    unit: 'K',
    percent: 45.0,
    remaining: 550,
    trend: '+18.2%',
    isUp: true,
    color: 'emerald',
  },
};

export const MOCK_DAILY_CONSUMPTION = [
  { day: 'Jul 01', bandwidth: 1.2, storage: 12.1, build_minutes: 8, function_executions: 12 },
  { day: 'Jul 04', bandwidth: 1.8, storage: 12.2, build_minutes: 15, function_executions: 14 },
  { day: 'Jul 07', bandwidth: 2.4, storage: 12.3, build_minutes: 22, function_executions: 18 },
  { day: 'Jul 10', bandwidth: 3.1, storage: 12.4, build_minutes: 12, function_executions: 21 },
  { day: 'Jul 13', bandwidth: 2.9, storage: 12.5, build_minutes: 18, function_executions: 19 },
  { day: 'Jul 16', bandwidth: 4.2, storage: 12.6, build_minutes: 35, function_executions: 28 },
  { day: 'Jul 19', bandwidth: 3.8, storage: 12.7, build_minutes: 24, function_executions: 25 },
  { day: 'Jul 22', bandwidth: 5.1, storage: 12.7, build_minutes: 42, function_executions: 34 },
  { day: 'Jul 25', bandwidth: 4.6, storage: 12.8, build_minutes: 28, function_executions: 31 },
  { day: 'Jul 28', bandwidth: 5.4, storage: 12.8, build_minutes: 45, function_executions: 38 },
  { day: 'Jul 29', bandwidth: 6.0, storage: 12.8, build_minutes: 50, function_executions: 42 },
];

export const MOCK_WEEKLY_CONSUMPTION = [
  { week: 'W1 (Jul 01-07)', bandwidth: 8.5, storage: 12.2, build_minutes: 65, function_executions: 85 },
  { week: 'W2 (Jul 08-14)', bandwidth: 12.4, storage: 12.4, build_minutes: 85, function_executions: 110 },
  { week: 'W3 (Jul 15-21)', bandwidth: 14.8, storage: 12.6, build_minutes: 115, function_executions: 140 },
  { week: 'W4 (Jul 22-29)', bandwidth: 18.2, storage: 12.8, build_minutes: 135, function_executions: 175 },
];

export const MOCK_MONTHLY_CONSUMPTION = [
  { month: 'Jan', bandwidth: 28, storage: 8.5, build_minutes: 210, function_executions: 280 },
  { month: 'Feb', bandwidth: 32, storage: 9.2, build_minutes: 240, function_executions: 310 },
  { month: 'Mar', bandwidth: 30, storage: 9.8, build_minutes: 195, function_executions: 290 },
  { month: 'Apr', bandwidth: 36, storage: 10.5, build_minutes: 260, function_executions: 340 },
  { month: 'May', bandwidth: 38, storage: 11.2, build_minutes: 285, function_executions: 390 },
  { month: 'Jun', bandwidth: 40, storage: 12.0, build_minutes: 310, function_executions: 410 },
  { month: 'Jul', bandwidth: 42.5, storage: 12.8, build_minutes: 320, function_executions: 450 },
];

export const MOCK_TOP_CONSUMERS = [
  {
    id: 'c1',
    name: 'Frontend App (deployx-frontend)',
    type: 'Frontend',
    bandwidth: '18.2 GB',
    storage: '4.1 GB',
    buildMinutes: '140 mins',
    functionExecutions: '180K',
    sharePercent: 42.8,
    status: 'Active',
    color: 'bg-blue-500',
  },
  {
    id: 'c2',
    name: 'Backend API (deployx-api-service)',
    type: 'Backend',
    bandwidth: '14.5 GB',
    storage: '5.8 GB',
    buildMinutes: '110 mins',
    functionExecutions: '210K',
    sharePercent: 34.1,
    status: 'Active',
    color: 'bg-indigo-500',
  },
  {
    id: 'c3',
    name: 'Analytics Service (deployx-analytics)',
    type: 'Analytics',
    bandwidth: '6.8 GB',
    storage: '2.1 GB',
    buildMinutes: '45 mins',
    functionExecutions: '40K',
    sharePercent: 15.5,
    status: 'Active',
    color: 'bg-purple-500',
  },
  {
    id: 'c4',
    name: 'Queue Worker (deployx-queue-worker)',
    type: 'Worker',
    bandwidth: '3.0 GB',
    storage: '0.8 GB',
    buildMinutes: '25 mins',
    functionExecutions: '20K',
    sharePercent: 7.6,
    status: 'Idle',
    color: 'bg-sky-500',
  },
];

export const MOCK_MONTHLY_QUOTAS = [
  {
    id: 'q1',
    name: 'Bandwidth',
    used: '42.5 GB',
    remaining: '57.5 GB',
    limit: '100 GB',
    percent: 42.5,
    status: 'Healthy',
    exhaustionText: 'Expected to reach limit in 11 days.',
    color: 'bg-gradient-to-r from-blue-600 to-indigo-500',
    theme: 'bandwidth',
  },
  {
    id: 'q2',
    name: 'Storage',
    used: '12.8 GB',
    remaining: '37.2 GB',
    limit: '50 GB',
    percent: 25.6,
    status: 'Healthy',
    exhaustionText: 'Capacity remaining for ~45+ days.',
    color: 'bg-gradient-to-r from-purple-600 to-pink-500',
    theme: 'storage',
  },
  {
    id: 'q3',
    name: 'Build Minutes',
    used: '780 mins',
    remaining: '220 mins',
    limit: '1000 mins',
    percent: 78.0,
    status: 'Warning',
    exhaustionText: 'Expected to reach limit in 4 days.',
    color: 'bg-gradient-to-r from-orange-500 to-amber-500',
    theme: 'build_minutes',
  },
  {
    id: 'q4',
    name: 'Function Executions',
    used: '890K',
    remaining: '110K',
    limit: '1000K',
    percent: 89.0,
    status: 'Critical',
    exhaustionText: 'Expected to reach limit in 2 days.',
    color: 'bg-gradient-to-r from-rose-500 to-red-600',
    theme: 'function_executions',
  },
];

export const MOCK_USAGE_HISTORY = [
  {
    id: 'hist-1',
    date: '2026-07-29',
    resource: 'Bandwidth',
    used: '6.0 GB',
    remaining: '57.5 GB',
    limit: '100.0 GB',
    percentage: 42.5,
    status: 'Normal',
  },
  {
    id: 'hist-2',
    date: '2026-07-28',
    resource: 'Build Minutes',
    used: '45 Mins',
    remaining: '680 Mins',
    limit: '1000 Mins',
    percentage: 32.0,
    status: 'Normal',
  },
  {
    id: 'hist-3',
    date: '2026-07-27',
    resource: 'Functions',
    used: '38K',
    remaining: '550K',
    limit: '1000K',
    percentage: 45.0,
    status: 'Normal',
  },
  {
    id: 'hist-4',
    date: '2026-07-25',
    resource: 'Bandwidth',
    used: '78.2 GB',
    remaining: '21.8 GB',
    limit: '100.0 GB',
    percentage: 78.2,
    status: 'Nearing Limit',
  },
  {
    id: 'hist-5',
    date: '2026-07-22',
    resource: 'Build Minutes',
    used: '85 Mins',
    remaining: '680 Mins',
    limit: '1000 Mins',
    percentage: 85.0,
    status: 'Warning',
  },
  {
    id: 'hist-6',
    date: '2026-07-19',
    resource: 'Storage',
    used: '12.7 GB',
    remaining: '37.3 GB',
    limit: '50.0 GB',
    percentage: 25.4,
    status: 'Healthy',
  },
  {
    id: 'hist-7',
    date: '2026-07-16',
    resource: 'Functions',
    used: '28K',
    remaining: '550K',
    limit: '1000K',
    percentage: 42.0,
    status: 'Normal',
  },
  {
    id: 'hist-8',
    date: '2026-07-12',
    resource: 'Bandwidth',
    used: '3.8 GB',
    remaining: '57.5 GB',
    limit: '100.0 GB',
    percentage: 38.0,
    status: 'Healthy',
  },
  {
    id: 'hist-9',
    date: '2026-07-10',
    resource: 'Storage',
    used: '12.4 GB',
    remaining: '37.6 GB',
    limit: '50.0 GB',
    percentage: 24.8,
    status: 'Healthy',
  },
  {
    id: 'hist-10',
    date: '2026-07-08',
    resource: 'Build Minutes',
    used: '920 Mins',
    remaining: '80 Mins',
    limit: '1000 Mins',
    percentage: 92.0,
    status: 'Critical',
  },
  {
    id: 'hist-11',
    date: '2026-07-05',
    resource: 'Functions',
    used: '410K',
    remaining: '590K',
    limit: '1000K',
    percentage: 41.0,
    status: 'Normal',
  },
  {
    id: 'hist-12',
    date: '2026-07-01',
    resource: 'Bandwidth',
    used: '2.1 GB',
    remaining: '97.9 GB',
    limit: '100.0 GB',
    percentage: 2.1,
    status: 'Healthy',
  },
];

export const MOCK_USAGE_ALERTS = [
  {
    id: 'alt-1',
    title: 'Function Execution Quota Exceeded',
    description: 'Serverless invocation concurrency hit 92% threshold across production endpoints.',
    severity: 'critical',
    timestamp: '10 mins ago',
    affectedResource: 'Functions',
    suggestedAction: 'Upgrade serverless concurrency limit or throttle burst rates.',
    actionLabel: 'Increase Quota',
    isRead: false,
  },
  {
    id: 'alt-2',
    title: 'High Bandwidth Consumption Detected',
    description: 'High edge traffic spike detected on deployx-frontend CDN asset endpoint (78% limit).',
    severity: 'warning',
    timestamp: '1 hour ago',
    affectedResource: 'Bandwidth',
    suggestedAction: 'Enable edge Gzip/Brotli compression and asset caching headers.',
    actionLabel: 'Configure Caching',
    isRead: false,
  },
  {
    id: 'alt-3',
    title: 'CI/CD Build Minutes Warning',
    description: 'Concurrent preview deployment builds triggered 78% monthly minute allocation.',
    severity: 'warning',
    timestamp: '3 hours ago',
    affectedResource: 'Build Minutes',
    suggestedAction: 'Cancel redundant feature branch builds and prune stale workflows.',
    actionLabel: 'Prune Workflows',
    isRead: true,
  },
  {
    id: 'alt-4',
    title: 'Storage Optimization Completed',
    description: 'Automated 30-day log purging successfully freed 8.4 GB of database disk storage.',
    severity: 'healthy',
    timestamp: '5 hours ago',
    affectedResource: 'Storage',
    suggestedAction: 'Maintain current automated retention policy.',
    actionLabel: 'View Retention',
    isRead: true,
  },
  {
    id: 'alt-5',
    title: 'System Health Check Passed',
    description: 'All edge routers, SSL certificates, and container instances operate within normal parameters.',
    severity: 'information',
    timestamp: '1 day ago',
    affectedResource: 'Infrastructure',
    suggestedAction: 'No immediate action required.',
    actionLabel: 'View Health Logs',
    isRead: true,
  },
];

export const MOCK_OPTIMIZATION_TIPS = [
  {
    id: 'tip-1',
    title: 'Reduce unused deployments',
    description: 'Automatically prune stale preview environments and temporary git feature branch deployments.',
    estimatedSavings: '12 GB',
    monthlyCostSavings: '≈ $8/month',
    priority: 'Medium Priority',
    impact: 'High Impact',
    difficulty: 'Easy',
    timeRequired: '2 mins',
    actionLabel: 'Configure Retention',
    icon: 'Rocket',
  },
  {
    id: 'tip-2',
    title: 'Delete old build logs',
    description: 'Set automated 30-day log purging retention policies to free up infrastructure storage.',
    estimatedSavings: '8.4 GB',
    monthlyCostSavings: '≈ $5/month',
    priority: 'High Priority',
    impact: 'Medium Impact',
    difficulty: 'Easy',
    timeRequired: '1 min',
    actionLabel: 'Purge Logs',
    icon: 'Terminal',
  },
  {
    id: 'tip-3',
    title: 'Compress edge static assets',
    description: 'Enable automatic Brotli/Gzip compression and WebP image optimization at edge CDN nodes.',
    estimatedSavings: '28 GB',
    monthlyCostSavings: '≈ $18/month',
    priority: 'High Priority',
    impact: 'High Impact',
    difficulty: 'Medium',
    timeRequired: '5 mins',
    actionLabel: 'Optimize Edge',
    icon: 'Zap',
  },
  {
    id: 'tip-4',
    title: 'Archive inactive repositories',
    description: 'Move dormant repositories and retired staging instances to cold storage to reduce quota consumption.',
    estimatedSavings: '45 GB',
    monthlyCostSavings: '≈ $29/month',
    priority: 'Low Priority',
    impact: 'Medium Impact',
    difficulty: 'Hard',
    timeRequired: '15 mins',
    actionLabel: 'View Projects',
    icon: 'Archive',
  },
];

/* ─────────────────────────────────────────────────────────────
   FORECAST USAGE
   Frontend prediction: project current daily rate to end of month.
   Formula:
     dailyRate     = currentUsed / dayOfMonth
     forecastUsed  = dailyRate × totalDaysInMonth
     forecastPct   = (forecastUsed / limit) × 100
───────────────────────────────────────────────────────────── */
function buildForecast({ id, currentUsed, limit, unit }) {
  const now           = new Date();
  const dayOfMonth    = now.getDate();
  const totalDays     = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
  const dailyRate     = currentUsed / dayOfMonth;
  const forecastUsed  = parseFloat((dailyRate * totalDays).toFixed(1));
  const currentPct    = parseFloat(((currentUsed / limit) * 100).toFixed(1));
  const forecastPct   = parseFloat(Math.min((forecastUsed / limit) * 100, 110).toFixed(1));
  return {
    id,
    unit,
    limit,
    currentUsed,
    currentPercent: currentPct,
    forecastUsed:   Math.min(forecastUsed, limit + limit * 0.1), // cap at 110% for display
    forecastPercent: forecastPct,
  };
}

export const MOCK_FORECAST_USAGE = [
  buildForecast({ id: 'bandwidth',           currentUsed: 42.5, limit: 100,  unit: 'GB'   }),
  buildForecast({ id: 'storage',             currentUsed: 12.8, limit: 50,   unit: 'GB'   }),
  buildForecast({ id: 'build_minutes',       currentUsed: 320,  limit: 1000, unit: 'Mins' }),
  buildForecast({ id: 'function_executions', currentUsed: 450,  limit: 1000, unit: 'K'    }),
];

export const MOCK_USAGE_SPIKES = [
  { id: 'spike-1', date: 'Jul 29, 2026', resource: 'Bandwidth', peakUsage: '6.0 GB', reason: 'Viral social media campaign', severity: 'High' },
  { id: 'spike-2', date: 'Jul 22, 2026', resource: 'Bandwidth', peakUsage: '5.1 GB', reason: 'New feature release', severity: 'Medium' },
  { id: 'spike-3', date: 'Jul 28, 2026', resource: 'Build Minutes', peakUsage: '45 mins', reason: 'Hotfix deployment cycle', severity: 'Low' },
  { id: 'spike-4', date: 'Jul 29, 2026', resource: 'Function Executions', peakUsage: '42K', reason: 'Batch processing job', severity: 'Medium' },
  { id: 'spike-5', date: 'Jul 16, 2026', resource: 'Bandwidth', peakUsage: '4.2 GB', reason: 'Data migration', severity: 'Low' }
];
