export const ACTIONS = {
  VIEW_PROJECT: 'VIEW_PROJECT',
  VIEW_DEPLOYMENT: 'VIEW_DEPLOYMENT',
  VIEW_DOMAIN: 'VIEW_DOMAIN',
  UPDATE_BILLING: 'UPDATE_BILLING',
  RETRY_DEPLOYMENT: 'RETRY_DEPLOYMENT',
  VIEW_USER: 'VIEW_USER',
  VIEW_LOG: 'VIEW_LOG',
};
